### ISSUE TITLE
Crear BD de audios

### ISSUE THREAD

**Issue by josearangos** [josearangos/VST#5]
- [x] duración maximo 6 segundos.
- [x] formato .wav
- [x] frecuencia de grabación 16khz
- [x] Guardar en la unidad en el drive
- [x] Usar el mismo programa de grabación. (Audacity)
- [x]  100 audios
- [x] crear un archivo con el contenido de los audios en texto "lo que se dice".

**Comment by josearangos** [comment]
200

**Comment by cdanmontoya** [comment]
Mis audios:
https://drive.google.com/open?id=1LgxlY4WpHx523ebAtRQDUijb7rwuv1y4

De los 400, 139 tienen transcripción. El modelo no requiere de la transcripción para el entrenamiento.

**Comment by cdanmontoya** [comment]
Ya León montó sus audios. 
Procedo a cerrar el issue.
